### ISSUE TITLE
自動ワールド再生成機能の追加

### ISSUE THREAD

**Issue by ryuuta0217** [ryuuta0217/UnknownNetworkCore#53]
# 要件
* リセット日時の設定はコマンドから(初回のみ)
* 作業終了後、Discordにて次回リセット日時の設定を通知 (Actionを使用する)
* リセット前、リセット後に実行されるスクリプト機能
* 自動でバックアップを取る

# 具体的な処理
```java
MVWorldManager manager = net.unknown.core.dependency.MultiverseCore.getInstance().getMVWorldManager();
// 再生成対象のワールドをすべてアンロードする manager.unloadWorld(worldName, true);
// バックアップを取る(プレイヤーデータも含める) (可能ならばMultiverse-Inventoriesのインベントリ情報も含める)
// 再生成対象のワールドをロードする manager.loadWorld(worldName);
// 再生成する manager.regenWorld(worldName, useSeed, useRandomSeed, seed, keepGameRules);
```

# 各ファイル等
`automatic-regenerations.yml`
```yml
scripts:
    resource:
        before: "resource-regeneration-before.js"
        after: "resource-regeneration-after.js"
    resource_nether:
        before: "resource-regeneration-before.js"
        after: "resource-regeneration-after.js"
    resource_the_end:
        before: "resource-regeneration-before.js"
        after: "resource-regeneration-after.js"
schedules:
    2024-08-15: # リセットは常に0時になった時点で行うので日付のみ
        worlds: ["resource", "resource_nether", "resource_the_end"]
        seed: UnknownNetworkResource20240815
```

`resource-regeneration-before.js`
```js
const PlayerData = net.unknown.survival.data.PlayerData;
PlayerData.loadExists();
PlayerData.getAll().forEach(data => {
    data.getHomeData().getGroups().forEach((groupName, group) => {
        group.getHomes().forEach((homeName, home) => {
            if (home.worldName().equals(worldName)) {
                group.deleteHome(home);
                // 現状のPlayerData実装にはbulk deleteする方法がなく、毎回非同期で保存が走るので先にBulk Delete実装する
            }
        });
    });
});
```

`resource-regeneration-after.js`
```js
// 再生成後は特にすることないな？
```
